### PR TITLE
Add autocompletion for fish shell

### PR DESCRIPTION
**Pull request by functionalStoic**
Fixes #5 

@waveaccounting should definitely get the credit

- Adds test necessary for Fish shell autocompletion based on request here by @RasPhilCo :
https://github.com/oclif/plugin-autocomplete/pull/5#issuecomment-534771852

Hope it helps move it along as I'm excited about Fish shell autocompletion for the Twilio CLI

### CODE REVIEW

**Comment by RasPhilCo** [comment]
Taking a look! Can you merge in master so it'll run the latest suite? Thanks!

**Comment by pksunkara** [comment]
@functionalStoic You need any help?

**Comment by functionalStoic** [comment]
@pksunkara Sure, I haven't been able to get back to it because of current obligations. Thanks!

**Comment by RasPhilCo** [comment]
Cleaning up - if you think this PR is still valid, reopen it. Thanks!

**Comment by p-dealwis** [comment]
@RasPhilCo I would like to help out with this. Can you please reopen it?

**Comment by Shurtu-gal** [comment]
@RasPhilCo this is something which is needed for our project. Any hopes for re-opening this.

**Comment by cristiand391** [comment]
hey @Shurtu-gal 👋🏼 
we don't have any plans to add official support for fish in the near future.

I wrote an oclif plugin to generate a `carapace` spec, you can use it with `carapace-spec` to get shell completion in fish for any oclif CLI:
https://github.com/cristiand391/oclif-carapace-spec-plugin

**Comment by AayushSaini101** [comment]
@cristiand391 
Thanks, i am following the readme for the carapace-spec plugin. Where can I download the carapace-spec, i checked this doc https://carapace-sh.github.io/carapace-bin/install.html and installed the carapace bin but cannot able to find the link of carapace-spec, 

but i cannot able to execute caraspace-gen command 
image
can you help me how to download proper binary or provide me the link thanks

**Comment by cristiand391** [comment]
@AayushSaini101 ah sorry, I'll update the readme to point to it. 
`carapace-spec` is the required binary, get it from GH releases:
https://github.com/carapace-sh/carapace-spec/releases

I use https://github.com/marcosnils/bin to manage bins from GH, or just download `carapace-spec` and put it into your PATH.

**Comment by AayushSaini101** [comment]
> @AayushSaini101 ah sorry, I'll update the readme to point to it. `carapace-spec` is the required binary, get it from GH releases: https://github.com/carapace-sh/carapace-spec/releases
> 
> I use https://github.com/marcosnils/bin to manage bins from GH, or just download `carapace-spec` and put it into your PATH.

thanks i downloaded the caraspace-spec which is the entry point to execute the carapace-gen
image

**Comment by cristiand391** [comment]
You only need the `carapace-spec` bin in your `PATH`, no other carapace bin is required.

Screenshot 2025-03-28 at 15 39 39
dowload the build for your machine and unpack it to get the binary ⬇️ 

Screenshot 2025-03-28 at 15 39 06

I think you dowloaded the source code.

**Comment by AayushSaini101** [comment]
Thanks a lot @cristiand391 binary added to path, carapace-gen command is still not found 
image

**Comment by cristiand391** [comment]
@AayushSaini101 

that should be `<cli> carapace-gen`, I'll update the readme.

Example with our `sf` CLI:
1. install plugin: `sf plugins install @cristiand391/oclif-carapace-spec-plugin`
2. run `sf carapace-gen`
Screenshot 2025-03-28 at 15 53 43

**Comment by AayushSaini101** [comment]
Thanks a lot got it

**Pull request closed without merging**
